version: "3.9"

services:
  go-redis-k8s:
    container_name: go-redis-k8s
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
  redis:
    container_name: redis
    image: redis:${REDIS_VERSION}
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --loglevel warning
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 5s
      timeout: 3s
      retries: 5