version: "3.9"

services:
  go-redis-k8s:
    container_name: go-redis-k8s
    image: 01092002/go-redis-k8s:1.0.0
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
  redis:
    container_name: redis
    image: redis:7.2-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 5s
      timeout: 3s
      retries: 5